apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellodocker-deployment
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: hellodocker
  template:
    metadata:
      labels:
        app: hellodocker
    spec:
      containers:
      - name: hellodocker
        image: kiranch97/hellodocker:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hellodocker-service
spec:
  selector:
    app: hellodocker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
